### ISSUE TITLE
File missing Initiate.ps1

### ISSUE THREAD

**Issue by HBGworksworksworks** [microsoft/Validate-DCB#19]
File missing Initiate.ps1

**Comment by dcuomo** [comment]
@HBGworksworksworks - Initiate is no longer necessary.  The workflow should now be:
- Install-Module Validate-DCB
- Validate-DCB

The UI will launch enabling you to create and export the configuration file.

Are you seeing documentation outdated?

**Comment by cookiejc** [comment]
The documentation still states to use initiate.ps1 to run the tests

**Comment by dcuomo** [comment]
Gotcha.  I just updated the documentation 75488aa

**Comment by dcuomo** [comment]
@cookiejc and @HBGworksworksworks could you please confirm that this solves the issue?

**Comment by cookiejc** [comment]
@dcuomo Looks good to me thanks. The new version is proving very useful!

**Comment by dcuomo** [comment]
@cookiejc - Thanks!  Please let us know if you have additional suggestions.
