### ISSUE TITLE
$expectedLimit Should be $expectedLimitMB

### ISSUE THREAD

**Issue by jaromirk** [microsoft/Validate-DCB#22]
![image](https://user-images.githubusercontent.com/9829838/68476348-b8c4ab00-022a-11ea-985c-1253f8b249ba.png)

https://github.com/microsoft/Validate-DCB/blob/fb27696b5612d0da732fb2d279a6eed905c8c6e6/Tests/unit/modal.unit.tests.ps1#L894

**Comment by dcuomo** [comment]
Good catch. Could you submit a PR to the dev branch?

**Comment by jaromirk** [comment]
Sure. Will do once I'll get to pc.

Sent from phone. Typos expected, hopefully still readable.

________________________________

**Comment by dcuomo** [comment]
@jaromirk  - I pushed the necessary changes and will close this issue. Thanks for testing and finding this issue!
