### ISSUE TITLE
Deployment Option doesn't check for Azure RM Modules

### ISSUE THREAD

**Issue by dcuomo** [microsoft/Validate-DCB#27]
![image](https://user-images.githubusercontent.com/12801954/69697383-1bc19900-1097-11ea-90e3-8d5997e91d2b.png)

**Comment by JamesKehr** [comment]
I don't know if this is fixed yet or not. Here's my suggestion...

```
if (-NOT (Get-Command Get-AzureRmAutomationModule -EA SilentlyCOntinue))
{
    Install-Module AzureRM.Automation -MinimumVersion 6.1.1 -Force
}
```


The gotcha with this is you need the newer version of PowerShellGet to download modules from PSGallery. Which requires an update to NuGet.

```
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name PowerShellGet -MinimumVersion 2.2.4.1 -Force
```

And then... you have to restart PowerShell. Because PowerShellGet won't work until the console is restarted.

A more robust version.

```
# make sure PowerShellGet is version 2.2.4
$psgVer = (Get-Module -ListAvailable PowerShellGet).Version

$updatePSG = $false

if ($psgVer -is [array])
{
    $psgVer = $psgVer | Where-Object {$_.Major -ge 2 -and $_.Minor -ge 2 -and $_.Build -ge 4}
}

if ($psgVer.Major -lt 2)
{
    $updatePSG = $true
}
elseif (($psgVer.Major -eq 2 -and $psgVer.Minor -lt 2) -or ($psgVer.Major -eq 2 -and $psgVer.Minor -eq 2 -and $psgVer.Build -lt 4))
{
    $updatePSG = $true
}
elseif (-NOT $psgVer)
{
    $updatePSG = $true
}

if ($updatePSG)
{
    Write-Host "Updating PowerShellGet for PSGallery compatibility."
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
    Install-Module -Name PowerShellGet -MinimumVersion 2.2.4.1 -Force

    # restart the script in a new console or PowerShellGet will not work
    $argument = @"
    -noprofile -nologo -noexit -ExecutionPolicy Unrestricted -File .\Validate-DCB.ps1 <...insert params...>
"@

    Write-Output "args: $argument"
    Start-Process powershell -WorkingDirectory $scriptPath -ArgumentList $argument -WindowStyle Normal

    Start-Sleep 2
    exit
}
```

**Comment by dcuomo** [comment]
@JamesKehr - So normally we just add this to the manifest and it takes a bunch of these down. I'm not sure for this as I believe this is a lesser used code path and would prefer not to balloon out the required/automatically downloaded modules.

Perhaps we could simply add a static check to the launch_deploy pre-check to see if the module is available. If not, fail a test and the user can install manually with Install-Module AzureRM.Automation. What do you think?

![image](https://user-images.githubusercontent.com/12801954/95693775-f1ab9380-0be2-11eb-9084-814db752f598.png)

**Comment by dcuomo** [comment]
Won't fix unless required
