### ISSUE TITLE
Config File must contain the AllNodes Hashtable

### ISSUE THREAD

**Issue by JamesKehr** [microsoft/Validate-DCB#31]
This test fails on multi-node clusters since AllNodes is defined as an array in the config file.

`$AllNodes    = @()`

$configData.AllNodes.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array

The test needs to look at the first element in the array. Or look through the array. Or check whether it's an array. Or some combination of the above.

Example fix:

`        ### Verify configData contains the AllNodes HashTable
        It "[Config File]-[AllNodes] Config File must contain the AllNodes Hashtable" {
            $configData.AllNodes[0] | Should BeOfType System.Collections.Hashtable
        }`

**Comment by dcuomo** [comment]
Hi James - I confirmed a multi-node cluster works fine on my system. Is this a multi-cluster environment? In that case i have seen an incompatibility and there's a helper to properly format in the examples.

Could you please post your config file?

**Comment by JamesKehr** [comment]
I do not have access to that config file anymore. I'll open this back up if I run into it again.
