### ISSUE TITLE
Error during new Live Migration Limit test

### ISSUE THREAD

**Issue by phinnay** [microsoft/Validate-DCB#35]
Seeing an error running Validate-DCB on servers, not sure how to troubleshoot

`
[+] [SUT: servername]-[SMB Adapter: STORE-D]-[Noun: SMBServerNetworkInterface] SMB Client must report RDMA Capable 2ms
      [-] Should have an Live Migration limit of 750 MBps 1ms
        ParameterBindingException: A positional parameter cannot be found that accepts argument '1'.
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Validate-DCB\20191128.2.2.82\tests\unit\modal.unit.tests.ps1: line 902

`

**Comment by JamesKehr** [comment]
There's a bug in this section of code. Caused mainly by what I suspect is a mix of PowerShell and Pester parsing problems.

You can manually update the code to fix the issue until an fix is pushed. I was going to submit an issue for it, but you beat me to the punch.

1. Get the base module path using this command.

`(Get-Module Validate-DCB -ListAvailable).Path`


2. Open VS Code or PowerShell ISE as Administrator. They must be open as admin or you cannot modify the file.

3. Navigate to \<module path\>\Tests\unit and open modal.unit.tests.ps1

4. Scroll down to line 892 and change the interior of the Switch statement to look like the code below.

There are two sets of changes:
- The It "" comments have a verbiage update.
- Parentheses added around "$expectedLimitMB + 1" -> ($expectedLimitMB + 1)


```
                            {$_ -le 10000000000} {
                                $expectedLimitMB = (((($thisPolicy.BandwidthPercentage / 100) * .6) * $AdapterLinkSpeed) / 8) / 1000000
                                It "Should have a Live Migration limit of less than equal to $expectedLimitMB MBps" {
                                    $SMBBandwidthLimit.BytesPerSecond / 1MB | Should BeLessThan ($expectedLimitMB + 1)
                                }
                            }

                            {$_ -gt 10000000000} {
                                $expectedLimitMB = (((($thisPolicy.BandwidthPercentage / 100) * .6) * $AdapterLinkSpeed) / 8) / 1000000
                                It "Should have an Live Migration limit of less than equal to 750 MBps" {
                                    $SMBBandwidthLimit.BytesPerSecond / 1MB | Should BeLessThan ($expectedLimitMB + 1)
                                }
                            }
```

5. Save the file and run Validate-DCB.


That should take care of the error.

**Comment by phinnay** [comment]
Thank you so much! Worked like a charm. 

Validation tools like this are SO important, thank you for putting the time into keeping this one working :D

**Comment by JamesKehr** [comment]
Glad to help.

**Comment by dcuomo** [comment]
@phinnay thanks for reporting and @JamesKehr thanks for helping.

This was fixed but ultimately had a few more issues 👎 After this commit, i'm not aware of any additional issues.
95d4df4713036897d01c1a5e0de52c5bf1b8878e
