### ISSUE TITLE
NetAdapter Name for the virtual NIC is named the same as the VMNetworkAdapter name

### ISSUE THREAD

**Issue by aricbernard** [microsoft/Validate-DCB#51]
When executing Validate-DCB, using the UI as the mechanism for parameter input, I have tried many different combinations including renaming adapters etc. however I cannot overcome this error.  I fear that this is further causing additional errors.

Configuration information resulting in the error:
- Server hardware include 2 physical ports which are teamed into a virtual switch "management_switch"
- Physical ports are named Management-1 and Management-2
- VMNetworkAdapters for the management OS have been created for Management, Storage1, and Storage2

Configuration attempt 1 to bypass the error:
- Change the name of the NetAdapters from 'vEthernet (Storage1)' and 'vEthernet (Storage1)' to Storage1 and Storage2 respectivley
- This results in the same error.

**Comment by dcuomo** [comment]
Hi @aricbernard I believe the issue is that the vNIC name reported by ```Get-VMNetworkAdapter -ManagementOS``` and ```Get-NetAdapter``` are not matching. This is a best practice to simplify diagnostic issues. To resolve this test use ```Rename-NetAdapter``` to match the Get-NetAdapter output to that of the Get-VMNetworkAdapter output.

**Comment by dcuomo** [comment]
Assuming this is closed. Can reopen if not resolved.
