### ISSUE TITLE
Incorrect Mellanox Driver Version Shown for Dell EMC Solutions for Microsoft Azure Stack HCI Solution

### ISSUE THREAD

**Issue by jlgandy2** [microsoft/Validate-DCB#52]
When using Microsoft Validate-DCB on Dell EMC Solutions for Microsoft Azure Stack HCI Solutions with Mellanox NICs, we see a recommendation to install a version of the Mellanox driver that has not been certified or even available for download from Dell. 

https://github.com/microsoft/Validate-DCB/blob/master/helpers/drivers/drivers.psd1
        @{ IHV = 'Mellanox' ; DriverFileName = 'mlx5.sys'      ; MinimumDriverVersion = '2.60.21096.0'  }  # ConnectX-4

Is there a way to add a check if Dell EMC Solutions for Microsoft Azure Stack HCI Solution use the driver version shown in the [Support Matrix for Microsoft HCI Solutions](https://www.dell.com/support/kbdoc/en-us/000126014/support-matrix-for-dell-emc-solutions-for-microsoft-azure-stack-hci)?

**Comment by dcuomo** [comment]
2.60 (or later) is the current Microsoft recommendation and given Mellanox released an updated driver, it suggests that they also recommend updating. Please follow up with Dell to  understand why they've not released the driver to customers.
